# Generated by Django 4.1.7 on 2023-04-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogentry_tags_delete_tag_blogentry_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
